# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='entity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='entity.Entity', verbose_name='to'),
            preserve_default=False,
        ),
    ]
