# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171008_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default=1, max_length=255, verbose_name='caption'),
            preserve_default=False,
        ),
    ]
