# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to', to='entity.Entity', verbose_name='comment_to'),
        ),
    ]
