# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20171009_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
    ]
